services:
  # Frontend Service - Static Site with comprehensive routing
  - type: static
    name: urbansprout
    buildCommand: cd client && npm install --include=dev && npm run build
    staticPublishPath: ./client/dist
    routes:
      # Rewrite all non-asset routes to index.html for React Router
      - type: rewrite
        source: /*
        destination: /index.html
      # Handle static assets properly
      - type: rewrite
        source: /assets/*
        destination: /assets/:splat
      - type: rewrite
        source: /fonts/*
        destination: /fonts/:splat
      # Handle specific file extensions
      - type: rewrite
        source: "*.css"
        destination: /:splat
      - type: rewrite
        source: "*.js"
        destination: /:splat
      - type: rewrite
        source: "*.png"
        destination: /:splat
      - type: rewrite
        source: "*.jpg"
        destination: /:splat
      - type: rewrite
        source: "*.jpeg"
        destination: /:splat
      - type: rewrite
        source: "*.gif"
        destination: /:splat
      - type: rewrite
        source: "*.ico"
        destination: /:splat
      - type: rewrite
        source: "*.svg"
        destination: /:splat
      - type: rewrite
        source: "*.woff"
        destination: /:splat
      - type: rewrite
        source: "*.woff2"
        destination: /:splat
      - type: rewrite
        source: "*.ttf"
        destination: /:splat
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_API_BASE_URL
        value: https://urbansprout-backend.onrender.com/api
      - key: VITE_FIREBASE_API_KEY
        value: AIzaSyDyyL7LDD2DeZmfetNvzdY8QZ5-eUJqHwU
      - key: VITE_FIREBASE_AUTH_DOMAIN
        value: urbansprout-bc137.firebaseapp.com
      - key: VITE_FIREBASE_PROJECT_ID
        value: urbansprout-bc137
      - key: VITE_FIREBASE_STORAGE_BUCKET
        value: urbansprout-bc137.firebasestorage.app
      - key: VITE_FIREBASE_MESSAGING_SENDER_ID
        value: "793698516798"
      - key: VITE_FIREBASE_APP_ID
        value: "1:793698516798:web:e87815785ae0b3575d766f"